### ISSUE TITLE
Librispeech results

### ISSUE THREAD

**Issue by snsun** [Alexander-H-Liu/Listen-Attend-and-Spell-Pytorch#9]
Hi, 
I try to run this code on Librispeech 100h data. But the NN can not converge. The CER keeps high on the development set. Have you ever trained the NN on Librispeech corpus?

Thanks

**Comment by nvidiaman** [comment]
@snsun hello, did you get it working on timit and librispeech? Could you share you code if it is public? I am having trouble getting it work https://github.com/Alexander-H-Liu/Listen-Attend-and-Spell-Pytorch/issues/12. thank you.

**Comment by snsun** [comment]
Hi,

It didn't work either. I recommend this code for you if you want to try.
https://github.com/kaituoxu/Listen-Attend-Spell

Best
Sining

nvidiaman <notifications@github.com> 于2019年1月27日周日 上午10:41写道：

**Comment by snsun** [comment]
actually, I didn't run his code. But the author runs it on a Mandarin corpus, it works well. You can ask him some details.

**Comment by Alexander-H-Liu** [comment]
@snsun Sorry for the late reply,
I've noticed the issue you've mentioned and been working on rebasing the whole project recently to solve it.
Currently, I've finished an End-to-end ASR which can run on LibriSpeech (tested and confirmed), you may find it in the [dev branch](https://github.com/Alexander-H-Liu/Listen-Attend-and-Spell-Pytorch/tree/dev)
However, the decoding process and documentation are still in development with the limited time I have... sorry for that.
I'll update this issue as soon as I finish the progress remained.
Thank you.

**Comment by nvidiaman** [comment]
@Alexander-H-Liu with the new update the master branch has the main code i.e we don't need to use the dev branch?
